name: Create Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.3
      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: '9.0.x'
      - name: Build with dotnet
        run: dotnet publish Webp2Png/Webp2Png.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:PublishReadyToRun=true -p:PublishTrimmed=true
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: Webp2Png v${{ github.run_number }}
          tag_name: v${{ github.run_number }}
          draft: false
          prerelease: false
          files: Webp2Png/bin/Release/net9.0-windows/win-x64/publish/Webp2Png.exe
          body: |
            Webp2Png release build ${{ github.run_number }}
            
            Automated build from the master branch.