name: Create Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SIXLABORS_LICENSE_KEY: ${{ secrets.SIXLABORS_LICENSE_KEY }}
    steps:
      - uses: actions/checkout@v6
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '11.0.x'
          dotnet-quality: 'preview'
      - name: Build with dotnet
        run: dotnet publish Webp2Png/Webp2Png.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:PublishReadyToRun=true -p:PublishTrimmed=true
        
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v3
        with:
          name: Webp2Png v${{ github.run_number }}
          tag_name: v${{ github.run_number }}
          draft: false
          prerelease: false
          files: Webp2Png/bin/Release/net11.0-windows/win-x64/publish/Webp2Png.exe
          body: |
            Webp2Png release build ${{ github.run_number }}
            
            Automated build from the master branch.